import Head from "next/head";
import { Footer } from "../../components/Footer";
import { Header } from "../../components/Header";
import { MainContent } from "../../components/MainContent";
import styles from '../../styles/Posts.module.css';

export default function AllPosts() {
    return (
        <>
            <Head>
                <title>Posts</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Header />
            <MainContent>
                <section className={styles.PostsContainer}>

                </section>
            </MainContent>
            <Footer />
        </>
    );
}