import Head from "next/head";
import { getFileBySlug, getFiles } from "../../lib/mdx";
import { MDXRemote } from "next-mdx-remote";
import styles from '../../styles/SlugPage.module.css';
import { Header } from "../../components/Header";
import Image from "next/image";



// -> ![text](/imageToShow.jpg "title")

export default function Post(props) {
    
    return (
        <>
            <Head>
                <title>{props.frontMatter.title}</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Header />
            <section className={styles.mainContentContainer}>
                <article className={styles.articleContainer}>
                    <p className={styles.articleDate}>{props.frontMatter.date}</p>
                    <h1 className={styles.articleTitle}>{props.frontMatter.title}</h1>
                    <span className={styles.articleAuthor}>
                        {"  By " + props.frontMatter.author}
                    </span>
                    <div className={styles.mainImageContainer}>
                        <Image
                            src={`/${props.frontMatter.main_image}`}
                            width={1000}
                            height={500}
                            className={styles.ImageMain}
                            alt={"main image"}
                        />
                    </div>
                    <div className={styles.articleContent}>
                        <MDXRemote {...props.source} />
                    </div>
                    {/* <article className={styles.intrestedContainer}>
                        <p>Lorem</p>
                    </article> */}

                </article>
            </section>
        </>
    );
}

export async function getStaticProps({ params }) {
    const { source, frontMatter } = await getFileBySlug(params.slug);
    return {
        props: {
            source,
            frontMatter
        }
    }
}

export async function getStaticPaths() {
    const array = await getFiles();
    const paths = array.map(post => ({
        params: {
            slug: post.replace(/\.mdx/, "")
        }
    }));
    return {
        paths,
        fallback: false
    }
}