import { useState } from "react";
import { ArticleTarget } from "../../components/ArticleTarget";
import { Footer } from "../../components/Footer";
import { Header } from "../../components/Header";
import { MainContent } from "../../components/MainContent";
import { URL_API } from "../../API/api";
import { Button } from "../../components/Button";
import { ToogleCategories } from "../../components/ToogleCategories";
import Head from "next/head";
import styles from '../../styles/Posts.module.css';

export default function Posts({ posts }) {

    const [filterModal, setFilterModal] = useState(false);
    const [postList, setPostsList] = useState(posts);
    function setFilter(categories = []) {
        console.log(posts)
        if (categories.length === 0) {
            setPostsList(posts);
            return
        };
        let res = [];
        categories.forEach((category) => {
            posts.forEach((post) => {
                if (post.categories.includes(category)) {
                    if (!res.includes(post)) {
                        res = [...res, post];
                    }
                }
            })
        })
        setPostsList(res);
    }

    return (
        <>
            <Head>
                <title>Posts</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Header />
            <MainContent>
                <section className={styles.postsContainer}>
                    {
                        !filterModal && <Button theme={'success'} text='FILTER' onSubmit={() => setFilterModal(!filterModal)} />
                    }
                    <article>
                        {
                            postList.map(post => <ArticleTarget {...post} key={post.postName} />)
                        }
                    </article>
                </section>
                {
                    filterModal && <Aside setFilterModal={setFilterModal} setFilter={setFilter} />
                }
            </MainContent>
            <Footer />
        </>
    );
}

const Aside = ({ setFilterModal, setFilter }) => {
    const [activeCategories, setActiveCategories] = useState([]);
    function handleFilter() {
        setFilter(activeCategories);
    }
    return (
        <aside className={styles.PostsSearchBar}>
            <h3>Filtro</h3>
            <div className={styles.PostsSearchBarInputContainer}>
                <ToogleCategories state={activeCategories} setState={setActiveCategories} />
            </div>
            <div
                className={styles.PostsSearchBarButtonsContainer}
            >
                <Button theme={'success'} text='Filter' className={styles.PostsSearchBarButton} onSubmit={handleFilter} />
                <Button theme={'danger'} text='Close' className={styles.PostsSearchBarButton} onSubmit={() => setFilterModal(false)} />
            </div>
        </aside>
    );
}

export const getStaticProps = async () => {
    const data = await fetch(`${URL_API}/posts`);
    const posts = await data.json();
    return {
        props: { posts }
    }
}
