import Head from "next/head";
import { Footer } from "../../components/Footer";
import { Header } from "../../components/Header";
import { MainContent } from "../../components/MainContent";
import styles from '../../styles/About.module.css';
import photo from '../../assets/userPhoto.png';
import Image from "next/image";
import { SocialNetworks } from "../../components/SocialNetworks";


export default function About() {
    return (
        <>
            <Head>
                <title>About Me</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Header />
            <MainContent>
                <section className={styles.aboutContainer}>
                    <h4 className={styles.greeting}>Hey There!</h4>
                    <article className={styles.me}>
                        <div className={styles.mePhotoContainer}>
                            <Image src={photo} alt="me" width={150} height={150}/>
                        </div>
                        <div className={styles.meInfoContainer}>
                            <p className={styles.meInfoText}>
                            </p>
                        </div>
                    </article>
                    <p style={{ margin: "0px" }} className={styles.meInfoText}>
                        
                    </p>
                    <span className={styles.meInfoFooter}>
                        Do you want to see more about my work?
                        <br />
                        Look at my portfolio <a className={styles.link} href={"https://www.alexisdev.tech"} target="__blank"> Here!</a>
                    </span>
                    <span className={styles.meInfoFooter}>
                        Contactamos?
                        <br />
                        <br />
                        <SocialNetworks />
                    </span>

                </section>
            </MainContent>
            <Footer />
        </>
    );
}