import Head from 'next/head'
import { ArticleTarget } from '../components/ArticleTarget';
import { Footer } from '../components/Footer';
import { Header } from '../components/Header'
import { LastPost } from '../components/LastPost';
import { MainContent } from '../components/MainContent';
import { getAllFilesMetadata, getLastPostMetaData } from '../lib/mdx';
import styles from "../styles/Home.module.css";


export default function Home( { posts, lastPost } ) {
  return (
    <div>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <MainContent>
        <section className={styles.postsSection}>
          <LastPost {...lastPost}/>
          <article>
          <div className={styles.morePostTitleContainer}>
                <h3>
                   More Posts
                </h3>
            </div>
            {
              posts.map((post) => <ArticleTarget {...post} key={post.slug} />              )
            }
          </article>
        </section>
      </MainContent>
      <Footer />
    </div>
  )
}

export async function getStaticProps(){
  const posts = await getAllFilesMetadata();
  const lastPost = await getLastPostMetaData();
  return {
    props: { posts, lastPost }
  }
}

