import Head from 'next/head'
import { useEffect, useState } from 'react';
import { ArticleTarget } from '../components/ArticleTarget';
import { Footer } from '../components/Footer';
import { Header } from '../components/Header'
import { LastPost } from '../components/LastPost';
import { MainContent } from '../components/MainContent';
import { SuscribeAlert } from '../components/SuscribedAlert';
import { getAllFilesMetadata, getLastPostMetaData } from '../lib/mdx';
import styles from "../styles/Home.module.css";


export default function Home({ posts, lastPost }) {

  const [showSuscribeAlert, setShowSuscribeAlert] = useState(false);

  // useEffect(() => {
  //   window.fetch('http://localhost:3000/api/home', { method: 'GET' })
  //     .then(response => response.json())
  //     .then(console.log)
  //     .catch((err) => {
  //       console.log(err);
  //     })
  // }, [])

  const handleSuscribe = () => {
    setShowSuscribeAlert(true);
    setTimeout(() => {
      setShowSuscribeAlert(false);
    }, 2000)
  }

  return (
    <div>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <MainContent handleSuscribe={handleSuscribe}>
        {
          showSuscribeAlert && <SuscribeAlert />
        }
        <section className={styles.postsSection}>
          <LastPost {...lastPost} />
          <article>
            <div className={styles.morePostTitleContainer}>
              <h3>
                More Posts
              </h3>
            </div>
            {
              posts.map((post) => <ArticleTarget {...post} key={post.slug} />)
            }
          </article>
        </section>
      </MainContent>
      <Footer />
    </div>
  )
}

export async function getStaticProps() {
  const posts = await getAllFilesMetadata();
  const lastPost = await getLastPostMetaData();
  return {
    props: { posts, lastPost }
  }
}

